baseURL = "http://www.kwyse.com/cv/"
languageCode = "en"
title = "Krishan Wyse"
theme = "hugo-devresume-theme"

[params]
author = "Krishan Wyse"
description = "Krishan Wyse's CV"

primaryColor = "#0892d0"
textPrimaryColor = "#292929"

[params.profile]
enable = true
name = "Krishan Wyse"
tagline = "Senior Software Engineer"
avatar = "avatar.png"

[params.contact]
enable = true
location = "London, UK"

[[params.contact.list]]
icon = "fas fa-globe"
url = "https://www.kwyse.com"
text = "www.kwyse.com"

[params.skills]
enable = true

[[params.skills.list]]
title = "Languages"
[[params.skills.list.items]]
details = "Java/Scala"
[[params.skills.list.items]]
details = "Rust"
[[params.skills.list.items]]
details = "C/C++"

[[params.skills.list]]
title = "Design"
[[params.skills.list.items]]
details = "Systems architecture"

[params.education]
enable = true

[[params.education.list]]
degree = "BSc Computer Science with Software Engineering"
university = "Brunel University London"
dates = "2011 - 2015"

[params.languages]
enable = true

[[params.languages.list]]
name = "English"
level = "Native"

[params.summary]
enable = true
text = "Software engineer with 5 years professional experience holding a first-class honours degree in computer science."

[params.experience]
enable = true

[[params.experience.list]]
title = "Senior Software Engineer"
dates = "July 2018 - Present"
company = "FIS (formerly Worldpay)"
details = "We are building the next generation payments gateway for organisations large and small. My team builds backend alternative payment and customer due diligence services in Scala using a test-first approach and a focus on fully-automated infrastructure operations."

[[params.experience.list]]
title = "Software Engineer"
dates = "May 2017 - July 2018"
company = "Curve"
details = "Curve was the card to end us carrying multiple credit and debit cards. The card itself and mobile app communicated with the backend services my team wrote in PHP and Go. Our codebases encompassed payment processing, reporting, analytics, and fraud detection.\n\nSome of my focal points were:"
[[params.experience.list.items]]
details = "Doubling our KYC true-positive rates by fine-tuning our data capturing schemes"
[[params.experience.list.items]]
details = "Building the waitlist for the consumer launch that dealt with consistently-increasing volumes"
[[params.experience.list.items]]
details = "Designing our move to a microservices-based architecture"

[[params.experience.list]]
title = "Technology Analyst, Credit Risk"
dates = "July 2015 - April 2017"
company = "Goldman Sachs"
details = "The credit risk technology team was comprised of forecasting and reporting. As part of the forecasting division, my team wrote tooling to perform ad-hoc pricing adjustments, web-apps to expose our tooling to the quantitative analysts, and responded to regulation mandates.\n\nMy tenure saw me:"
[[params.experience.list.items]]
details = "Migrate on-premises pricing adjustment records to more reliable cloud-based storage"
[[params.experience.list.items]]
details = "Build a bespoke heat map for our server farms that was used by the operations team during the Brexit referendum"

[[params.experience.list]]
title = "QA Engineer"
dates = "August 2013 - August 2014"
company = "Chelsea Apps Factory"
details = "We built enterprise mobile apps for the likes of Allen & Overy, Tesco, and EDF Energy. QA was brought in from the initial product envisioning and writing requirements with the business analysis team, through to fleshing out stories with the development and design teams.\n\nHighlights of my internship included:"
[[params.experience.list.items]]
details = "Introducing automated testing for our front-end web apps with Ruby and Selenium"
[[params.experience.list.items]]
details = "Documenting and formalising the training processes on our manual QA processes"


[params.projects]
enable = true

[[params.projects.list]]
title = "Personal blog"
meta = "Website"
tagline = "Delivering educational content on general software development, game-related subjects, and personal development."

[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/kwyse"
title = "kwyse"
[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/krishanwyse"
title = "krishanwyse"
