baseURL = "https://www.kwyse.com/cv/"
languageCode = "en"
title = "Krishan Wyse"
theme = "hugo-devresume-theme"

[params]
author = "Krishan Wyse"
description = "Krishan Wyse's CV"

primaryColor = "#0892d0"
textPrimaryColor = "#292929"

[params.profile]
enable = true
name = "Krishan Wyse"
tagline = "Software Engineer and Commerce Technologist"
avatar = "avatar.png"

[params.contact]
enable = true
location = "London, UK"

[[params.contact.list]]
icon = "fas fa-globe"
url = "https://www.kwyse.com"
text = "kwyse.com"

[params.footer]
copyright = "Krishan Wyse"

[params.education]
enable = true

[[params.education.list]]
degree = "BSc Computer Science with Software Engineering"
university = "Brunel University London"
dates = "2011 – 2015"

[params.skills]
enable = true

[[params.skills.list]]
title = "Technical"
[[params.skills.list.items]]
details = "Java/Scala/Akka"
[[params.skills.list.items]]
details = "Rust"
[[params.skills.list.items]]
details = "C/C++"
[[params.skills.list.items]]
details = "Python/Ruby"
[[params.skills.list.items]]
details = "AWS/Terraform"

[[params.skills.list]]
title = "Design"
[[params.skills.list.items]]
details = "Systems architecture"
[[params.skills.list.items]]
details = "Distributed systems"
[[params.skills.list.items]]
details = "Reactive systems"

[[params.skills.list]]
title = "Methods"
[[params.skills.list.items]]
details = "TDD/BDD"
[[params.skills.list.items]]
details = "Agile/Scrum"
[[params.skills.list.items]]
details = "Reactive programming"

[[params.skills.list]]
title = "Domains"
[[params.skills.list.items]]
details = "Payment processing"
[[params.skills.list.items]]
details = "Financial risk"

[params.certifications]
enable = true

[[params.certifications.list]]
title = "Lightbend Certified Reactive Architect"
meta = "Expires December 2022"
provider = "Lightbend, Inc."

[params.languages]
enable = true

[[params.languages.list]]
name = "English"
level = "Native"

[params.summary]
enable = true
text = "Software engineer with seven years of professional experience holding a first-class honours degree in computer science.  Keen reader, writer, photographer, cook, explorer, and tinkerer.  Follow me on Twitter to see what I'm working on."

[params.experience]
enable = true

[[params.experience.list]]
title = "Senior Software Engineer"
dates = "July 2018 – Present"
company = "FIS (formerly Worldpay)"
details = "We build the next generation payments gateway for organisations large and small. My team craft backend alternative payment solutions in Scala using a test-first approach and fully-automated infrastructure with a focus on resilience."

[[params.experience.list]]
title = "Software Engineer"
dates = "May 2017 – July 2018"
company = "Curve"
details = "Curve consolidated all of your credit and debit cards into one. The card itself and mobile app communicated with the backend services my team wrote in PHP and Go. Our codebases encompassed payment processing, reporting, analytics, and fraud detection.\n\nSome of my focal points were:"
[[params.experience.list.items]]
details = "Doubling our KYC true-positive rates by fine-tuning our data capturing schemes"
[[params.experience.list.items]]
details = "Building the waitlist for the B2C launch that dealt with consistently-increasing volumes"
[[params.experience.list.items]]
details = "Designing our transition to a microservices-based architecture"

[[params.experience.list]]
title = "Technology Analyst, Credit Risk"
dates = "July 2015 – April 2017"
company = "Goldman Sachs"
details = "The credit risk technology department comprised of forecasting and reporting. As part of the forecasting team, my team wrote tooling to perform ad-hoc pricing adjustments, web applications that exposed our tooling to quantitative analysts, and responded to regulation mandates.\n\nMy tenure saw me:"
[[params.experience.list.items]]
details = "Migrate on-prem pricing adjustment records to more resilient and available cloud-based storage"
[[params.experience.list.items]]
details = "Build bespoke heat maps for our compute farms to be used during crises events"

[[params.experience.list]]
title = "QA Engineer"
dates = "August 2013 – August 2014"
company = "Chelsea Apps Factory"
details = "Chelsea Apps Factory built enterprise mobile apps for the likes of Allen & Overy, Tesco, and EDF Energy. QA was brought in from the initial product envisioning and requirements gathering, through to fleshing out stories during the design phase and working with the developers for the life of the project.\n\nHighlights of my internship included:"
[[params.experience.list.items]]
details = "Introducing automated testing for the front-end web applications with Ruby and Selenium"
[[params.experience.list.items]]
details = "Documenting and formalising the training regime on QA processes"

[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-twitter-square"
url = "//twitter.com/KrishanWyse"
title = "KrishanWyse"
[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/kwyse"
title = "kwyse"
[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/krishanwyse"
title = "krishanwyse"
